### ISSUE TITLE
Installing R packages

### ISSUE THREAD

**Issue by Bimsayol** [trr266/trer#1]
Hi, below is the error message that I got while installing the R packages. What do I need to do? This is my first time working with R. 

Error in install.packages : ERROR: failed to lock directory ‘\\lipasto\kotidir01$\boyinlol\My Documents\R\R-4.0.5\library’ for modifying
Try removing ‘\\lipasto\kotidir01$\boyinlol\My Documents\R\R-4.0.5\library/00LOCK’

**Comment by towitter** [comment]
Try to follow the recommended solutions in your error message: Look for the lock file '00LOCK' in your path ‘\lipasto\kotidir01$\boyinlol\My Documents\R\R-4.0.5\library/', remove it, and try running the code again.

**Comment by Bimsayol** [comment]
Thank you
